name: My Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: lushengtao0115
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: lushengtao0115/lushengtao0115
          branch: master
